### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zpbrent**

### CODE REVIEW

**Comment by JamieSlome** [comment]
@zpbrent - thanks for the PR!

We no longer support updating the contents of the `README.md` through GitHub. I have gone ahead and made the update directly to our database.

We will of course be looking to support this functionality on-platform soon...

**Comment by zpbrent** [comment]
> @zpbrent - thanks for the PR!
> 
> We no longer support updating the contents of the `README.md` through GitHub. I have gone ahead and made the update directly to our database.
> 
> We will of course be looking to support this functionality on-platform soon...

@JamieSlome Thank you for the help. By the way, I just submitted a new vul for mongoose at https://www.huntr.dev/bounties/1-npm-mongoose/ . But the title "Disclosed a high risk Prototype Pollution in mongoose vulnerability in mongoose" contains duplicated "in mongoose", can you help me to delete the first "in mongoose" and make it to the right one "Disclosed a high risk Prototype Pollution vulnerability in mongoose", many thanks!

**Comment by JamieSlome** [comment]
@zpbrent - will get that sorted for you ASAP! 👍 

Cheers and great disclosure! 🍰

**Comment by JamieSlome** [comment]
Sorted...

**Comment by zpbrent** [comment]
> Sorted...

Great👍 @JamieSlome , many thanks for your kind help!

**Comment by JamieSlome** [comment]
@zpbrent - no worries, look forward to seeing more of your disclosures!

**Pull request closed without merging**
