### PR TITLE
Denial of Service (DoS) in desperado/xml-bundle (packagist) - 1

### PR DESCRIPTION
**Pull request by JamieSlome**
For the best experience when engaging in this conversation, visit https://www.huntr.dev/bounties/1-packagist-desperado%2Fxml-bundle

### CODE REVIEW

**Comment by psmoros** [comment]
That's the first comment

**Comment by psmoros** [comment]
ddddd

**Comment by psmoros** [comment]
hello world

**Comment by psmoros** [comment]
why is this lgaaing

**Comment by psmoros** [comment]
that's a test

**Comment by psmoros** [comment]
hello worldƒ

**Comment by psmoros** [comment]
hi worldƒ

**Comment by psmoros** [comment]
what is this status?

**Comment by psmoros** [comment]
what the fuck..

**Comment by psmoros** [comment]
this is a test

**Comment by JamieSlome** [comment]
@psmoros - not too sure? Test.

**Comment by psmoros** [comment]
thel

**Pull request merged**
