### PR TITLE
WIP: Merging staging into master on `process-bounties`

### PR DESCRIPTION
**Pull request by benharvie**
- Addition of final step, merging staging into master on `process-bounties`
- Merged in #749

### CODE REVIEW

**Comment by adam-nygate** [comment]
@benharvie we should probably merge our WIP into a branch and not directly into staging, so that we can resolve conflicts and remove unnecessary files (e.g the bounties you've accidentally included)

**Comment by benharvie** [comment]
@adam-nygate no worries, I shall create an epic branch for this repo too for both our WIP's

**Comment by adam-nygate** [comment]
@benharvie can you remove the disclosures from this PR and resolve the conflicts so we can start the review?

**Comment by JamieSlome** [comment]
Resolving with a new PR. Closing.

**Pull request closed without merging**
