### PR TITLE
Cross Site-Scripting (XSS) in Froxlor

### PR DESCRIPTION
**Pull request by b1nslashsh**
## ✍️ Description

`Froxlor` is a server administration software . Developed by experienced server administrators, this panel simplifies the effort of managing your hosting platform. this pakage in vulnerable for `xss`

https://github.com/Froxlor/Froxlor
http://www.froxlor.org/

## 💥 Impact
xss payloads executed.
## ✅ Checklist
- [x] _Created and populated the `README.md` and `vulnerability.json` files_
- [x] _Provided the repository URL and any applicable [permalinks]([https://help.github.com/en/github/managing-files-in-a-repository/getting-permanent-links-to-files](https://help.github.com/en/github/managing-files-in-a-repository/getting-permanent-links-to-files))_
- [x] _Defined all the applicable weaknesses ([CWEs]([https://cwe.mitre.org/](https://cwe.mitre.org/)))_
- [x] _Proposed the CVSS vector items i.e. User Interaction, Attack Complexity_
- [x] _Checked that the vulnerability affects the latest version of the package released_
- [x] _Checked that a fix does not currently exist that remediates this vulnerability_
- [x] _Complied with all applicable laws_

### CODE REVIEW

**Review by Mik317 — APPROVED** [review]
Hi @b1nslashsh :smile:,
I was able to get `HTML injection` but not `XSS` since the CSP is blocking the payload on the `local installation` :

Screenshot from 2020-10-15 16-15-36
Screenshot from 2020-10-15 16-17-21

Could you eventually bypass it (it would lead probably to `account takeover` and this higher indeed the severity :+1: )

Cheers,
Mik

**Comment by b1nslashsh** [comment]
Hey @Mik317 
Thanks for your response 
I didn't think CSP can be Bypassed ,
So is that good to change topic from `xss` to just `HTML injection` ? 

Regards,
Muhaimin

**Comment by Mik317** [comment]
Hi @b1nslashsh :smile:,
no worries at all and it should fine changing it as you suggested 😉 

Cheers,
Mik

**Comment by 418raj** [comment]
Hey @b1nslashsh cheers for the disclosure! In this case because HTML injection is fairly low severity and it isn't in a registry, we can't really take this, but I'd encourage you to try and bypass the CSP with policy injection or modifying the payload to increase the severity, and reopen if you manage this. Also worth reporting to the repo maintainers. Cheers 👍

**Pull request closed without merging**
