### PR TITLE
Test JSON validator on vulnerability.json

### PR DESCRIPTION
**Pull request by toufik-airane**
Test JSON validator on vulnerability.json with Ajv package.

### CODE REVIEW

**Comment by adam-nygate** [comment]
Thanks for this @toufik-airane just going to clean this up a bit and change the way it returns messages to PR's via https://developer.github.com/v3/checks/runs/

**Comment by toufik-airane** [comment]
Basically, the idea consists to have node.js scripts to rely on for basic actions like JSON validation, etc.

Also, I think the best place for these scripts could be in /.github/scripts/ for example, near the /.github/workflows/ it could deliver powerful automation.

**Comment by toufik-airane** [comment]
If you need any help feel free to reach me.

**Comment by adam-nygate** [comment]
For some reason, the workflow has stopped running, I'm going to see if opening a new PR fixes it

**Comment by toufik-airane** [comment]
Oh, I had the issue, I think we should specify the action in which case we should rerun the workflow.
https://developer.github.com/webhooks/event-payloads/#pull_request

**Comment by toufik-airane** [comment]
Screenshot 2020-06-17 at 16 31 28
https://developer.github.com/webhooks/event-payloads/#pull_request

**Comment by toufik-airane** [comment]
```
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
```

**Pull request closed without merging**
